cask_args appdir: '/Applications'

tap 'borkdude/brew'
tap 'hashicorp/tap'

brew 'bash-completion'
brew 'bat'
brew 'borkdude/brew/babashka'
brew 'borkdude/brew/jet'
brew 'claude-code'
brew 'clojure'
brew 'coreutils'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'httpie'
brew 'jq'
brew 'leiningen'
brew 'libyaml'
brew 'neovim'
brew 'node'
brew 'openssl'
brew 'pure'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'readline'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'tldr'
brew 'tmux'
brew 'uv'
brew 'vault'
brew 'wget'
brew 'xsv'
brew 'zsh'

cask 'cljstyle'
cask 'codex'
cask 'docker'
cask 'firefox'
cask 'font-source-code-pro'
cask 'ghostty'
cask 'google-chrome'
cask 'raycast'
cask 'rectangle'
cask 'spotify'
cask 'visual-studio-code'
